version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mongo-compose-network

  api-gateway:
    image: api-gateway:latest
    ports:
      - 8080:8080
    command: npm run start:dev
    volumes:
      - .:/opt/api-gateway
    networks:
      - mongo-compose-network

  micro-admin-backend:
    image: micro-admin-backend:latest
    ports:
      - 3000:3000
    command: npm run start:dev
    volumes:
      - ../micro-admin-backend:/opt/micro-admin-backend
    networks:
      - mongo-compose-network

  micro-challenges:
    image: micro-challenges:latest
    ports:
      - 3001:3001
    command: npm run start:dev
    volumes:
      - ../micro-challenges:/opt/micro-challenges
    networks:
      - mongo-compose-network

  micro-rankings:
    image: micro-rankings:latest
    ports:
      - 3002:3002
    command: npm run start:dev
    volumes:
      - ../micro-rankings:/opt/micro-rankings
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge